[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/proxy"
  to = "/.netlify/functions/proxy"
  status = 200

[[redirects]]
  from = "/index.html"
  to = "/network.html"
  status = 301

[[redirects]]
  from = "/"
  to = "/home.html"
  status = 200
